<script src="/js/vendor/jquery-1.11.3.min.js"></script>
	<script src="/js/vendor/bootstrap.min.js"></script>
	<script src="/js/owl.carousel.min.js"></script>
	<script src="/js/parallax.js"></script>
	<script src="/js/jquery.prettyPhoto.js"></script>
	<script src="//js/custom-form/jcf.js"></script>
	<script src="/js/custom-form/jcf.checkbox.js"></script>
	<script src="/js/custom-form/jcf.select.js"></script>
	<script src="/js/custom-form/jcf.radio.js"></script>
	<script src="/js/custom-form/jcf.file.js"></script>
	<script src="/js/appear.js"></script>
	<script src="http://maps.google.com/maps/api/js?sensor=false"></script>
	<script src="/js/gmap3.min.js"></script>
	<script src="/js/main.js"></script>